description: Helm chart for the HMCTS CCD Definition Store
name: ccd-definition-store-api
apiVersion: v2
home: https://github.com/hmcts/ccd-definition-store-api
version: 1.5.6
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
dependencies:
  - name: java
    version: 3.4.8
    repository: '@hmctspublic'
