description: Helm chart for the HMCTS CCD Definition Store
name: ccd-definition-store-api
home: https://github.com/hmcts/ccd-definition-store-api
version: 1.0.1
maintainers:
  - name: HMCTS CCD Dev Team
    email: ccd-devops@HMCTS.NET
