java:
  image: 'hmctspublic.azurecr.io/ccd/definition-store-api:latest'
  ingressHost: ccd-definition-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4451
  aadIdentityName: ccd
  autoscaling:
    enabled: false
    maxReplicas: 4
  keyVaults:
    ccd:
      secrets:
        - name: definition-store-api-POSTGRES-USER-V15
          alias: DEFINITION_STORE_DB_USERNAME
        - name: definition-store-api-POSTGRES-PASS-V15
          alias: DEFINITION_STORE_DB_PASSWORD
        - name: ccd-definition-s2s-secret
          alias: DEFINITION_STORE_IDAM_KEY
        - name: ccd-ELASTIC-SEARCH-URL
          alias: ELASTIC_SEARCH_HOST
        - name: ccd-ELASTIC-SEARCH-PASSWORD
          alias: ELASTIC_SEARCH_PASSWORD
        - name: storage-account-primary-connection-string
          alias: AZURE_STORAGE_CONNECTION_STRING
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    DEFINITION_STORE_DB_PORT: 5432
    DEFINITION_STORE_DB_NAME: ccd_definition_store
    DEFINITION_STORE_DB_HOST: ccd-definition-store-api-postgres-db-v15-{{ .Values.global.environment }}.postgres.database.azure.com
    DEFINITION_STORE_DB_OPTIONS: "?sslmode=require&gssEncMode=disable"
    DEFINITION_STORE_DB_MAX_POOL_SIZE: 25


    DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin,jui_webapp,pui_webapp,aac_manage_case_assignment,xui_webapp

    # Storage Account
    AZURE_STORAGE_BLOB_CONTAINER_REFERENCE: ccd-definition-store-api-imports-{{ .Values.global.environment }}
    AZURE_STORAGE_DEFINITION_UPLOAD_ENABLED: true
    AZURE_STORAGE_IMPORT_AUDITS_GET_LIMIT: 20

    ELASTIC_SEARCH_ENABLED: true
    ELASTIC_SEARCH_PORT: 9200
    ELASTIC_SEARCH_SCHEME: http
    ELASTIC_SEARCH_INDEX_SHARDS: 2
    ELASTIC_SEARCH_INDEX_SHARDS_REPLICAS: 1
    ELASTIC_SEARCH_FAIL_ON_IMPORT: true
    ELASTIC_SEARCH_DYNAMIC: true
    ELASTIC_SEARCH_CASE_INDEX_NAME_FORMAT: '%s_cases'
    ELASTIC_SEARCH_CASE_INDEX_MAPPING_FIELDS_LIMIT: 10000

    WELSH_TRANSLATION_ENABLED: true
    ENABLE_CASE_GROUP_ACCESS: true

    # Role-based authorization for CCD Admin Web
    ADMIN_WEB_AUTHORIZATION_ENABLED: false # Needs enabling once the appropriate roles are created in IdAM
    ADMIN_WEB_AUTHORIZATION_MANAGE_USER_PROFILE_0: ccd-import
    ADMIN_WEB_AUTHORIZATION_MANAGE_USER_ROLE_0: ccd-import
    ADMIN_WEB_AUTHORIZATION_MANAGE_DEFINITION_0: ccd-import
    ADMIN_WEB_AUTHORIZATION_IMPORT_DEFINITION_0: ccd-import
    ADMIN_WEB_AUTHORIZATION_MANAGE_WELSH_TRANSLATION_0: manage-translations
    ADMIN_WEB_AUTHORIZATION_LOAD_WELSH_TRANSLATION_0: load-translations

    IDAM_USER_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    USER_PROFILE_HOST: http://ccd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    TS_TRANSLATION_SERVICE_HOST: http://ts-translation-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
